export interface StandardFieldDefinition {
  group: string;
  key: string;
  name: string;
  desc: string;
}

export const STANDARD_FIELDS_DEF: StandardFieldDefinition[] = [
  { group: 'Khách hàng', key: 'customer.id', name: 'Mã khách hàng (ID)', desc: 'Chuỗi. Bắt buộc để định danh.' },
  { group: 'Khách hàng', key: 'customer.name', name: 'Tên khách hàng', desc: 'Chuỗi. Mặc định "Khách lẻ" nếu trống.' },
  { group: 'Khách hàng', key: 'customer.phone', name: 'Số điện thoại', desc: 'Chuỗi.' },
  { group: 'Khách hàng', key: 'customer.address', name: 'Địa chỉ', desc: 'Chuỗi.' },
  { group: 'Khách hàng', key: 'customer.email', name: 'Email', desc: 'Chuỗi.' },
  { group: 'Khách hàng', key: 'customer.createdAt', name: 'Ngày tạo tài khoản', desc: 'Chuỗi ISO. Mặc định là hiện tại.' },
  { group: 'Khách hàng', key: 'customer.group', name: 'Nhóm khách hàng', desc: 'Chuỗi. Nhóm phân loại như khách VIP, khách sỉ, khách lẻ.' },
  { group: 'Khách hàng', key: 'customer.gender', name: 'Giới tính', desc: 'Chuỗi. nam/nữ hoặc male/female.' },
  { group: 'Khách hàng', key: 'customer.birthday', name: 'Ngày sinh', desc: 'Chuỗi YYYY-MM-DD.' },
  { group: 'Khách hàng', key: 'customer.customerId', name: 'Mã phụ khách hàng', desc: 'Chuỗi. Mã định danh bổ sung từ POS.' },
  { group: 'Khách hàng', key: 'customer.notes', name: 'Ghi chú khách hàng', desc: 'Chuỗi. Các lưu ý về sở thích, thói quen của khách.' },
  { group: 'Khách hàng', key: 'customer.points', name: 'Điểm tích lũy', desc: 'Số nguyên. Điểm thưởng của khách hàng.' },
  { group: 'Khách hàng', key: 'customer.level', name: 'Hạng thành viên', desc: 'Chuỗi. Cấp bậc hội viên (Bạc, Vàng, Kim Cương...).' },
  { group: 'Khách hàng', key: 'customer.totalSpend', name: 'Tổng tiền đã mua', desc: 'Số nguyên. Tổng chi tiêu tích lũy của khách.' },

  { group: 'Sản phẩm', key: 'product.id', name: 'Mã hệ thống (ID)', desc: 'Chuỗi. Bắt buộc.' },
  { group: 'Sản phẩm', key: 'product.name', name: 'Tên sản phẩm', desc: 'Chuỗi. Bắt buộc.' },
  { group: 'Sản phẩm', key: 'product.sku', name: 'Mã SKU', desc: 'Chuỗi. Mã vạch, mã kho.' },
  { group: 'Sản phẩm', key: 'product.price', name: 'Giá bán lẻ', desc: 'Số nguyên. Mặc định 0.' },
  { group: 'Sản phẩm', key: 'product.quantity', name: 'Số lượng / Tồn kho', desc: 'Số nguyên. Mặc định 0.' },
  { group: 'Sản phẩm', key: 'product.imageUrl', name: 'Đường dẫn ảnh chính', desc: 'Chuỗi URL.' },
  { group: 'Sản phẩm', key: 'product.barcode', name: 'Mã vạch (Barcode)', desc: 'Chuỗi barcode.' },
  { group: 'Sản phẩm', key: 'product.costPrice', name: 'Giá vốn', desc: 'Số nguyên. Phục vụ tính biên lợi nhuận.' },
  { group: 'Sản phẩm', key: 'product.weight', name: 'Khối lượng (gram)', desc: 'Số nguyên. Phục vụ tính phí vận chuyển.' },
  { group: 'Sản phẩm', key: 'product.category', name: 'Danh mục', desc: 'Chuỗi. Phân loại sản phẩm.' },
  { group: 'Sản phẩm', key: 'product.description', name: 'Mô tả chi tiết', desc: 'Chuỗi HTML hoặc Markdown mô tả sản phẩm.' },
  { group: 'Sản phẩm', key: 'product.shortDescription', name: 'Mô tả ngắn', desc: 'Chuỗi mô tả tóm tắt sản phẩm.' },
  { group: 'Sản phẩm', key: 'product.wholesalePrice', name: 'Giá sỉ / bán buôn', desc: 'Số nguyên. Mặc định 0.' },
  { group: 'Sản phẩm', key: 'product.lastImportedPrice', name: 'Giá nhập gần nhất', desc: 'Số nguyên. Giá nhập kho của lần nhập mới nhất.' },
  { group: 'Sản phẩm', key: 'product.isComposite', name: 'Sản phẩm combo/set', desc: 'Boolean. Xác định là sản phẩm đóng gói từ nhiều thành phần.' },
  { group: 'Sản phẩm', key: 'product.compositeProducts', name: 'Mảng sản phẩm thành phần', desc: 'Mảng (Array). Danh sách ID + số lượng các thành phần cấu thành combo.' },
  { group: 'Sản phẩm', key: 'product.color', name: 'Màu sắc (Color)', desc: 'Chuỗi. Thuộc tính màu sắc của biến thể.' },
  { group: 'Sản phẩm', key: 'product.size', name: 'Kích thước (Size)', desc: 'Chuỗi. Thuộc tính kích thước của biến thể.' },
  { group: 'Sản phẩm', key: 'product.material', name: 'Chất liệu', desc: 'Chuỗi. Thuộc tính chất liệu cấu thành sản phẩm.' },
  { group: 'Sản phẩm', key: 'product.brand', name: 'Thương hiệu / Nhãn hiệu', desc: 'Chuỗi. Hãng sản xuất của sản phẩm.' },
  { group: 'Sản phẩm', key: 'product.unit', name: 'Đơn vị tính', desc: 'Chuỗi. Ví dụ: cái, chiếc, hộp, kg...' },
  { group: 'Sản phẩm', key: 'product.supplier', name: 'Nhà cung cấp', desc: 'Chuỗi. Tên đơn vị phân phối/cung cấp.' },
  { group: 'Sản phẩm', key: 'product.status', name: 'Trạng thái kinh doanh', desc: 'Chuỗi. Trạng thái bán (đang bán, ngừng bán).' },
  { group: 'Sản phẩm', key: 'product.isHidden', name: 'Ẩn sản phẩm', desc: 'Boolean. Trạng thái ẩn/hiện trên trang bán hàng.' },
  { group: 'Sản phẩm', key: 'product.isSellNegative', name: 'Cho phép bán âm kho', desc: 'Boolean. Vẫn cho tạo đơn khi tồn kho bằng 0.' },
  { group: 'Sản phẩm', key: 'product.variationId', name: 'ID phiên bản (Variation)', desc: 'Chuỗi. ID phân biệt các mẫu mã biến thể.' },
  { group: 'Sản phẩm', key: 'product.parentId', name: 'ID sản phẩm gốc', desc: 'Chuỗi. ID sản phẩm cha của biến thể.' },
  { group: 'Sản phẩm', key: 'product.images', name: 'Danh sách ảnh phụ', desc: 'Mảng chuỗi (Array) các URL ảnh liên quan.' },

  { group: 'Đơn hàng', key: 'order.id', name: 'Mã hệ thống (ID)', desc: 'Chuỗi. Khóa chính.' },
  { group: 'Đơn hàng', key: 'order.orderCode', name: 'Mã vận đơn (Hiển thị)', desc: 'Chuỗi mã code.' },
  { group: 'Đơn hàng', key: 'order.customer', name: 'Object Khách hàng', desc: 'Kế thừa logic map Khách hàng ở trên.' },
  { group: 'Đơn hàng', key: 'order.products', name: 'Mảng (Array) Sản phẩm', desc: 'Kế thừa logic map Sản phẩm ở trên.' },
  { group: 'Đơn hàng', key: 'order.totalAmount', name: 'Tổng giá trị', desc: 'Số nguyên. Mặc định 0.' },
  { group: 'Đơn hàng', key: 'order.discount', name: 'Giảm giá', desc: 'Số nguyên. Mặc định 0.' },
  { group: 'Đơn hàng', key: 'order.status', name: 'Trạng thái', desc: 'Chuỗi Enum. pending/completed/cancelled' },
  { group: 'Đơn hàng', key: 'order.createdAt', name: 'Ngày tạo đơn', desc: 'Chuỗi ISO. Mặc định là hiện tại.' },
  { group: 'Đơn hàng', key: 'order.notes', name: 'Ghi chú đơn', desc: 'Chuỗi.' },
  { group: 'Đơn hàng', key: 'order.paymentMethod', name: 'Phương thức thanh toán', desc: 'Chuỗi. Ví dụ: COD, Bank, Cash.' },
  { group: 'Đơn hàng', key: 'order.shippingFee', name: 'Phí vận chuyển thực tế', desc: 'Số nguyên. Phí thực tế thu của khách.' },
  { group: 'Đơn hàng', key: 'order.codAmount', name: 'Số tiền thu hộ (COD)', desc: 'Số nguyên. Số tiền shipper thu hộ.' },
  { group: 'Đơn hàng', key: 'order.partnerFee', name: 'Phí đối tác / sàn', desc: 'Số nguyên. Phí dịch vụ sàn hoặc đối tác.' },
  { group: 'Đơn hàng', key: 'order.tags', name: 'Nhãn đơn (Tags)', desc: 'Mảng chuỗi (Array). Các nhãn phân loại đơn.' },
  { group: 'Đơn hàng', key: 'order.salesChannel', name: 'Kênh bán hàng', desc: 'Chuỗi. Kênh phát sinh đơn hàng (Facebook, Shopee...).' },
  { group: 'Đơn hàng', key: 'order.warehouseId', name: 'Mã kho hàng (ID)', desc: 'Chuỗi. ID kho hàng thực hiện xuất đơn.' },
  { group: 'Đơn hàng', key: 'order.statusName', name: 'Tên trạng thái (Tiếng Việt)', desc: 'Chuỗi. Tên trạng thái đầy đủ (Ví dụ: Chờ xác nhận, Đã hủy...).' },
  { group: 'Đơn hàng', key: 'order.receivedAtShop', name: 'Ngày nhận tại shop', desc: 'Chuỗi ISO. Thời gian đơn được chuyển sang trạng thái đã nhận tại shop.' },
  { group: 'Đơn hàng', key: 'order.creator', name: 'Người tạo đơn', desc: 'Chuỗi. Tên hoặc ID nhân viên lên đơn.' },
  { group: 'Đơn hàng', key: 'order.conversationId', name: 'Mã hội thoại (Chat ID)', desc: 'Chuỗi. Link sang Pancake Chat.' },
  { group: 'Đơn hàng', key: 'order.pageId', name: 'Mã Fanpage (Page ID)', desc: 'Chuỗi. Trang Facebook/Instagram phát sinh đơn.' },
];

export const DEFAULT_MAPPINGS: Record<string, Record<string, { selected: string; suggestions: string[] }>> = {
  'pancake-pos': {
    'customer.id': { selected: 'id', suggestions: ['id', 'customer_id'] },
    'customer.name': { selected: 'name', suggestions: ['name', 'customer_name'] },
    'customer.phone': { selected: 'phone', suggestions: ['phone', 'phone_number', 'customer_phone'] },
    'customer.address': { selected: 'address', suggestions: ['address', 'customer_address'] },
    'customer.email': { selected: 'email', suggestions: ['email', 'customer_email'] },
    'customer.createdAt': { selected: 'inserted_at', suggestions: ['createdAt', 'created_at', 'inserted_at'] },
    'customer.group': { selected: 'group', suggestions: ['group', 'customer_group', 'level'] },
    'customer.gender': { selected: 'gender', suggestions: ['gender', 'sex'] },
    'customer.birthday': { selected: 'birthday', suggestions: ['birthday', 'birth_day'] },
    'customer.customerId': { selected: 'display_id', suggestions: ['customer_id', 'display_id', 'code'] },
    'customer.notes': { selected: 'note', suggestions: ['notes', 'note', 'ghi_chu'] },
    'customer.points': { selected: 'points', suggestions: ['points', 'diem', 'diem_tich_luy'] },
    'customer.level': { selected: 'level', suggestions: ['level', 'level_name', 'hang_thanh_vien'] },
    'customer.totalSpend': { selected: 'total_spend', suggestions: ['total_spend', 'total_amount', 'tong_chi_tieu'] },

    'product.id': { selected: 'id', suggestions: ['id', 'product_id'] },
    'product.name': { selected: 'name', suggestions: ['name', 'title'] },
    'product.sku': { selected: 'sku', suggestions: ['sku', 'product_sku'] },
    'product.price': { selected: 'price', suggestions: ['price'] },
    'product.quantity': { selected: 'quantity', suggestions: ['quantity', 'inventory', 'stock'] },
    'product.imageUrl': { selected: 'image_url', suggestions: ['imageUrl', 'image_url', 'image'] },
    'product.barcode': { selected: 'barcode', suggestions: ['barcode', 'bar_code'] },
    'product.costPrice': { selected: 'cost_price', suggestions: ['costPrice', 'cost_price', 'importPrice', 'import_price'] },
    'product.weight': { selected: 'weight', suggestions: ['weight', 'product_weight'] },
    'product.category': { selected: 'category_name', suggestions: ['category', 'category_name', 'product_category'] },
    'product.description': { selected: 'description', suggestions: ['description', 'mo_ta'] },
    'product.shortDescription': { selected: 'short_description', suggestions: ['short_description', 'mo_ta_ngan'] },
    'product.wholesalePrice': { selected: 'wholesale_price', suggestions: ['wholesale_price', 'gia_si'] },
    'product.lastImportedPrice': { selected: 'last_imported_price', suggestions: ['last_imported_price', 'gia_nhap_cuoi'] },
    'product.isComposite': { selected: 'is_composite', suggestions: ['is_composite', 'composite'] },
    'product.compositeProducts': { selected: 'composite_products', suggestions: ['composite_products', 'compositeProducts'] },
    'product.color': { selected: 'color', suggestions: ['color', 'colour', 'mau', 'mau_sac'] },
    'product.size': { selected: 'size', suggestions: ['size', 'kich_thuoc', 'kich_co'] },
    'product.material': { selected: 'material', suggestions: ['material', 'chat_lieu'] },
    'product.brand': { selected: 'brand_name', suggestions: ['brand', 'brand_name', 'thuong_hieu'] },
    'product.unit': { selected: 'unit', suggestions: ['unit', 'don_vi', 'don_vi_tinh'] },
    'product.supplier': { selected: 'supplier', suggestions: ['supplier', 'nha_cung_cap'] },
    'product.status': { selected: 'status', suggestions: ['status', 'trang_thai'] },
    'product.isHidden': { selected: 'is_hidden', suggestions: ['is_hidden', 'hidden'] },
    'product.isSellNegative': { selected: 'is_sell_negative_variation', suggestions: ['is_sell_negative_variation', 'sell_negative'] },
    'product.variationId': { selected: 'id', suggestions: ['id', 'variation_id', 'product_id'] },
    'product.parentId': { selected: 'product_id', suggestions: ['product_id', 'parent_id'] },
    'product.images': { selected: 'images', suggestions: ['images', 'image_list', 'image_urls'] },

    'order.id': { selected: 'id', suggestions: ['id', 'order_id'] },
    'order.orderCode': { selected: 'order_code', suggestions: ['orderCode', 'order_code', 'code', 'order_id', 'id'] },
    'order.status': { selected: 'status', suggestions: ['status'] },
    'order.totalAmount': { selected: 'total_amount', suggestions: ['totalAmount', 'total_amount', 'total', 'price'] },
    'order.discount': { selected: 'discount', suggestions: ['discount'] },
    'order.createdAt': { selected: 'inserted_at', suggestions: ['createdAt', 'created_at', 'inserted_at'] },
    'order.notes': { selected: 'note', suggestions: ['notes', 'note', 'customer_note'] },
    'order.paymentMethod': { selected: 'payment_method', suggestions: ['paymentMethod', 'payment_method', 'payment_type'] },
    'order.shippingFee': { selected: 'shipping_fee', suggestions: ['shippingFee', 'shipping_fee', 'ship_fee'] },
    'order.codAmount': { selected: 'cod_amount', suggestions: ['codAmount', 'cod_amount', 'cod'] },
    'order.partnerFee': { selected: 'partner_fee', suggestions: ['partnerFee', 'partner_fee', 'fee'] },
    'order.tags': { selected: 'tag_names', suggestions: ['tags', 'tag_names', 'labels'] },
    'order.salesChannel': { selected: 'sales_channel', suggestions: ['salesChannel', 'sales_channel', 'channel', 'source'] },
    'order.warehouseId': { selected: 'warehouse_id', suggestions: ['warehouseId', 'warehouse_id', 'warehouse'] },
    'order.statusName': { selected: 'status_name', suggestions: ['status_name', 'statusName'] },
    'order.receivedAtShop': { selected: 'received_at_shop', suggestions: ['received_at_shop', 'received_at'] },
    'order.creator': { selected: 'creator', suggestions: ['creator', 'created_by'] },
    'order.conversationId': { selected: 'conversation_id', suggestions: ['conversation_id', 'chat_id'] },
    'order.pageId': { selected: 'page_id', suggestions: ['page_id', 'fanpage_id'] }
  },
  'kiotviet': {
    'customer.id': { selected: 'id', suggestions: ['id'] },
    'customer.name': { selected: 'name', suggestions: ['name'] },
    'customer.phone': { selected: 'contactNumber', suggestions: ['contactNumber'] },
    'customer.address': { selected: 'address', suggestions: ['address'] },
    'customer.email': { selected: 'email', suggestions: ['email'] },
    'customer.createdAt': { selected: 'createdDate', suggestions: ['createdDate'] },
    'customer.group': { selected: 'groupName', suggestions: ['groupName', 'customerGroupName'] },
    'customer.gender': { selected: 'gender', suggestions: ['gender'] },
    'customer.birthday': { selected: 'birthDate', suggestions: ['birthDate'] },
    'customer.customerId': { selected: 'code', suggestions: ['code'] },
    'customer.notes': { selected: 'comments', suggestions: ['comments', 'description'] },
    'customer.points': { selected: 'points', suggestions: ['points'] },
    'customer.level': { selected: 'level', suggestions: ['level'] },
    'customer.totalSpend': { selected: 'totalSpend', suggestions: ['totalSpend'] },

    'product.id': { selected: 'id', suggestions: ['id'] },
    'product.name': { selected: 'fullName', suggestions: ['fullName', 'name'] },
    'product.sku': { selected: 'code', suggestions: ['code'] },
    'product.price': { selected: 'basePrice', suggestions: ['basePrice'] },
    'product.quantity': { selected: 'onHand', suggestions: ['onHand'] },
    'product.imageUrl': { selected: 'images', suggestions: ['images'] },
    'product.barcode': { selected: 'barcode', suggestions: ['barcode'] },
    'product.costPrice': { selected: 'cost', suggestions: ['cost'] },
    'product.weight': { selected: 'weight', suggestions: ['weight'] },
    'product.category': { selected: 'categoryName', suggestions: ['categoryName'] },
    'product.description': { selected: 'description', suggestions: ['description'] },
    'product.shortDescription': { selected: 'shortDescription', suggestions: ['shortDescription'] },
    'product.wholesalePrice': { selected: 'wholesalePrice', suggestions: ['wholesalePrice'] },
    'product.lastImportedPrice': { selected: 'lastImportedPrice', suggestions: ['lastImportedPrice'] },
    'product.isComposite': { selected: 'isComposite', suggestions: ['isComposite'] },
    'product.compositeProducts': { selected: 'compositeProducts', suggestions: ['compositeProducts'] },
    'product.color': { selected: 'color', suggestions: ['color'] },
    'product.size': { selected: 'size', suggestions: ['size'] },
    'product.material': { selected: 'material', suggestions: ['material'] },
    'product.brand': { selected: 'brand', suggestions: ['brand'] },
    'product.unit': { selected: 'unit', suggestions: ['unit'] },
    'product.supplier': { selected: 'supplier', suggestions: ['supplier'] },
    'product.status': { selected: 'status', suggestions: ['status'] },
    'product.isHidden': { selected: 'isHidden', suggestions: ['isHidden'] },
    'product.isSellNegative': { selected: 'isSellNegative', suggestions: ['isSellNegative'] },
    'product.variationId': { selected: 'id', suggestions: ['id'] },
    'product.parentId': { selected: 'parentId', suggestions: ['parentId'] },
    'product.images': { selected: 'images', suggestions: ['images'] },

    'order.id': { selected: 'id', suggestions: ['id'] },
    'order.orderCode': { selected: 'code', suggestions: ['code'] },
    'order.status': { selected: 'status', suggestions: ['status'] },
    'order.totalAmount': { selected: 'totalPayment', suggestions: ['totalPayment'] },
    'order.discount': { selected: 'discount', suggestions: ['discount'] },
    'order.createdAt': { selected: 'createdDate', suggestions: ['createdDate'] },
    'order.notes': { selected: 'description', suggestions: ['description'] },
    'order.paymentMethod': { selected: 'paymentMethod', suggestions: ['paymentMethod'] },
    'order.shippingFee': { selected: 'shippingFee', suggestions: ['shippingFee'] },
    'order.codAmount': { selected: 'codAmount', suggestions: ['codAmount'] },
    'order.partnerFee': { selected: 'partnerFee', suggestions: ['partnerFee'] },
    'order.tags': { selected: 'tags', suggestions: ['tags'] },
    'order.salesChannel': { selected: 'saleChannelName', suggestions: ['saleChannelName', 'salesChannel'] },
    'order.warehouseId': { selected: 'branchId', suggestions: ['branchId', 'branch_id'] },
    'order.statusName': { selected: 'statusName', suggestions: ['statusName'] },
    'order.receivedAtShop': { selected: 'receivedDate', suggestions: ['receivedDate'] },
    'order.creator': { selected: 'creator', suggestions: ['creator'] },
    'order.conversationId': { selected: 'conversationId', suggestions: ['conversationId'] },
    'order.pageId': { selected: 'pageId', suggestions: ['pageId'] }
  },

  'pancake-chat': {
    'customer.id': { selected: 'id', suggestions: ['id', 'customer_id'] },
    'customer.name': { selected: 'customer_name', suggestions: ['customer_name', 'name', 'full_name'] },
    'customer.phone': { selected: 'customer_phone', suggestions: ['customer_phone', 'phone'] },
    'customer.createdAt': { selected: 'inserted_at', suggestions: ['inserted_at', 'created_at'] },
    'customer.notes': { selected: 'recent_note', suggestions: ['recent_note', 'note', 'ghi_chu'] },
    'order.id': { selected: 'order_id', suggestions: ['order_id', 'latest_order'] },
    'order.conversationId': { selected: 'id', suggestions: ['id', 'conversation_id'] },
    'order.pageId': { selected: 'page_id', suggestions: ['page_id'] },
    'order.creator': { selected: 'assignee_name', suggestions: ['assignee_name', 'staff_name', 'user_id'] },
    'order.tags': { selected: 'tags', suggestions: ['tags', 'labels'] },
    'order.status': { selected: 'status', suggestions: ['status', 'is_done'] },
    'order.notes': { selected: 'last_message', suggestions: ['last_message', 'snippet'] }
  }
};
